/**
 * Client tool configuration (Claude Code ~/.claude/settings.json, Codex ~/.codex/config.toml)
 * GET/POST /ccrelay/api/client-config
 */

import * as fs from "fs";
import * as http from "http";
import * as os from "os";
import * as path from "path";
import type { ProxyServer } from "../server/handler";

function sendJson(res: http.ServerResponse, status: number, data: unknown): void {
  // eslint-disable-next-line @typescript-eslint/naming-convention -- HTTP response header
  res.writeHead(status, { "Content-Type": "application/json" });
  res.end(JSON.stringify(data));
}

async function parseJsonBody<T>(req: http.IncomingMessage): Promise<T> {
  return new Promise((resolve, reject) => {
    let body = "";
    req.on("data", (chunk: Buffer) => {
      body += chunk.toString();
    });
    req.on("end", () => {
      try {
        resolve(JSON.parse(body || "{}") as T);
      } catch (err) {
        reject(err instanceof Error ? err : new Error(String(err)));
      }
    });
    req.on("error", reject);
  });
}

let serverInstance: ProxyServer | null = null;

export function setServer(server: ProxyServer | null): void {
  serverInstance = server;
}

const CLAUDE_SETTINGS = () => path.join(os.homedir(), ".claude", "settings.json");
const CODEX_CONFIG = () => path.join(os.homedir(), ".codex", "config.toml");

export type ClientConfigItemStatus = "ok" | "missing" | "wrong_target" | "invalid";

export interface ClientConfigItem {
  status: ClientConfigItemStatus;
  filePath: string;
  /** e.g. ANTHROPIC_BASE_URL or Codex base_url */
  currentValue?: string;
  /** For Codex, which model_provider is selected */
  modelProvider?: string;
  message?: string;
}

/** Optional Claude Code env overrides (CCRelay modelMap usually enough). */
export interface ClaudeDefaultModels {
  opus?: string;
  sonnet?: string;
  haiku?: string;
}

export interface ClientConfigGetResponse {
  expectedAnthropicBase: string;
  expectedCodexBaseUrl: string;
  port: number;
  claudeCode: ClientConfigItem;
  codex: ClientConfigItem;
  /** Parsed from settings.json env when file is readable */
  claudeDefaultModels: ClaudeDefaultModels;
}

/** localhost / 127.0.0.1 / ::1 and matching port */
export function isLocalProxyAnthropicBase(urlStr: string, port: number): boolean {
  const t = urlStr.trim();
  if (!t) {
    return false;
  }
  let u: URL;
  try {
    u = new URL(t);
  } catch {
    return false;
  }
  const h = u.hostname;
  if (h !== "localhost" && h !== "127.0.0.1" && h !== "[::1]" && h !== "::1") {
    return false;
  }
  const p = u.port ? parseInt(u.port, 10) : u.protocol === "https:" ? 443 : 80;
  if (p !== port) {
    return false;
  }
  return u.pathname === "" || u.pathname === "/";
}

export function isLocalProxyCodexBase(urlStr: string, port: number): boolean {
  const t = urlStr.trim();
  if (!t) {
    return false;
  }
  let u: URL;
  try {
    u = new URL(t);
  } catch {
    return false;
  }
  const h = u.hostname;
  if (h !== "localhost" && h !== "127.0.0.1" && h !== "[::1]" && h !== "::1") {
    return false;
  }
  const p = u.port ? parseInt(u.port, 10) : u.protocol === "https:" ? 443 : 80;
  if (p !== port) {
    return false;
  }
  return u.pathname === "/v1" || u.pathname === "/v1/";
}

/* eslint-disable @typescript-eslint/naming-convention -- Claude Code settings.json env object keys */
function buildClaudeDefaultEnv(port: number): Record<string, string | number> {
  return {
    ANTHROPIC_AUTH_TOKEN: "ccrelay_apikey_placehold_do_not_need_to_setup_here",
    ANTHROPIC_BASE_URL: `http://127.0.0.1:${port}`,
    API_TIMEOUT_MS: "3000000",
    CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC: 1,
  };
}
/* eslint-enable @typescript-eslint/naming-convention */

function readClaudeDefaultModelsFromFile(claudePath: string): ClaudeDefaultModels {
  if (!fs.existsSync(claudePath)) {
    return {};
  }
  try {
    const raw = fs.readFileSync(claudePath, "utf-8");
    const parsed = JSON.parse(raw) as { env?: Record<string, unknown> };
    const env = parsed.env || {};
    const s = (key: string): string | undefined => {
      const v = env[key];
      if (v === undefined || v === null) {
        return undefined;
      }
      if (typeof v === "string" || typeof v === "number") {
        return String(v);
      }
      return undefined;
    };
    return {
      opus: s("ANTHROPIC_DEFAULT_OPUS_MODEL"),
      sonnet: s("ANTHROPIC_DEFAULT_SONNET_MODEL"),
      haiku: s("ANTHROPIC_DEFAULT_HAIKU_MODEL"),
    };
  } catch {
    return {};
  }
}

function buildCodexTemplate(port: number): string {
  return `# Generated by CCRelay dashboard — Codex -> local proxy
model = "glm-5-turbo"
model_provider = "ccrelay"

[model_providers.ccrelay]
name = "CCRelay"
base_url = "http://127.0.0.1:${port}/v1"
`;
}

type ParsedTomlLite = {
  top: Record<string, string>;
  sections: Record<string, Record<string, string>>;
};

/** Minimal TOML parse for key = value and [table] (Codex config shape). */
export function parseTomlLite(content: string): ParsedTomlLite {
  const top: Record<string, string> = {};
  const sections: Record<string, Record<string, string>> = {};
  let current = "";
  for (const line of content.split(/\r?\n/)) {
    const t = line.trim();
    if (!t || t.startsWith("#")) {
      continue;
    }
    const section = t.match(/^\[([^\]]+)\]$/);
    if (section) {
      current = section[1];
      continue;
    }
    const eq = t.indexOf("=");
    if (eq === -1) {
      continue;
    }
    const key = t.slice(0, eq).trim();
    let val = t.slice(eq + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    if (current) {
      if (!sections[current]) {
        sections[current] = {};
      }
      sections[current][key] = val;
    } else {
      top[key] = val;
    }
  }
  return { top, sections };
}

function detectClaude(claudePath: string, port: number): ClientConfigItem {
  const filePath = claudePath;
  if (!fs.existsSync(claudePath)) {
    return { status: "missing", filePath };
  }
  const raw = fs.readFileSync(claudePath, "utf-8");
  let parsed: { env?: Record<string, unknown> };
  try {
    parsed = JSON.parse(raw) as { env?: Record<string, unknown> };
  } catch {
    return { status: "invalid", filePath, message: "Invalid JSON" };
  }
  const base = parsed.env?.ANTHROPIC_BASE_URL;
  if (base === undefined || base === null) {
    return { status: "missing", filePath, message: "ANTHROPIC_BASE_URL not set in env" };
  }
  if (typeof base !== "string" && typeof base !== "number") {
    return {
      status: "wrong_target",
      filePath,
      currentValue: JSON.stringify(base),
      message: "ANTHROPIC_BASE_URL must be a string",
    };
  }
  const s = String(base).trim();
  if (s === "") {
    return { status: "missing", filePath, message: "ANTHROPIC_BASE_URL not set in env" };
  }
  if (isLocalProxyAnthropicBase(s, port)) {
    return { status: "ok", filePath, currentValue: s };
  }
  return { status: "wrong_target", filePath, currentValue: s };
}

function detectCodex(codexPath: string, port: number): ClientConfigItem {
  const filePath = codexPath;
  if (!fs.existsSync(codexPath)) {
    return { status: "missing", filePath };
  }
  const raw = fs.readFileSync(codexPath, "utf-8");
  const toml = parseTomlLite(raw);
  const modelProvider = toml.top.model_provider;
  if (!modelProvider) {
    return { status: "missing", filePath, message: "model_provider not set" };
  }
  const sec = toml.sections[`model_providers.${modelProvider}`];
  const baseUrl = sec?.base_url;
  if (!baseUrl) {
    return { status: "missing", filePath, modelProvider, message: "base_url not set for provider" };
  }
  if (isLocalProxyCodexBase(baseUrl, port)) {
    return { status: "ok", filePath, currentValue: baseUrl, modelProvider };
  }
  return { status: "wrong_target", filePath, currentValue: baseUrl, modelProvider };
}

/**
 * GET /ccrelay/api/client-config
 */
export function handleGetClientConfig(_req: http.IncomingMessage, res: http.ServerResponse): void {
  if (!serverInstance) {
    sendJson(res, 503, { error: "Server not initialized" });
    return;
  }
  const port = serverInstance.getConfig().port;
  const expectedAnthropicBase = `http://127.0.0.1:${port}`;
  const expectedCodexBaseUrl = `http://127.0.0.1:${port}/v1`;
  const claudePath = CLAUDE_SETTINGS();
  const body: ClientConfigGetResponse = {
    expectedAnthropicBase,
    expectedCodexBaseUrl,
    port,
    claudeCode: detectClaude(claudePath, port),
    codex: detectCodex(CODEX_CONFIG(), port),
    claudeDefaultModels: readClaudeDefaultModelsFromFile(claudePath),
  };
  sendJson(res, 200, body);
}

type ApplyTarget = "claudeCode" | "codex";

/**
 * POST /ccrelay/api/client-config/apply
 * Body: { target, overwrite?, patchClaudeModelsOnly?, claudeDefaultModels? }
 */
export async function handleApplyClientConfig(
  req: http.IncomingMessage,
  res: http.ServerResponse
): Promise<void> {
  if (!serverInstance) {
    sendJson(res, 503, { error: "Server not initialized" });
    return;
  }
  const port = serverInstance.getConfig().port;
  const claudePath = CLAUDE_SETTINGS();
  const codexPath = CODEX_CONFIG();
  const existingClaude = detectClaude(claudePath, port);
  const existingCodex = detectCodex(codexPath, port);

  try {
    const body = await parseJsonBody<{
      target?: ApplyTarget;
      overwrite?: boolean;
      patchClaudeModelsOnly?: boolean;
      claudeDefaultModels?: { opus?: string; sonnet?: string; haiku?: string };
    }>(req);
    const target = body.target;
    const overwrite = Boolean(body.overwrite);
    if (target !== "claudeCode" && target !== "codex") {
      sendJson(res, 400, { status: "error", message: "target must be claudeCode or codex" });
      return;
    }

    if (target === "claudeCode" && body.patchClaudeModelsOnly) {
      const m = body.claudeDefaultModels;
      if (!m || typeof m !== "object") {
        sendJson(res, 400, { status: "error", message: "claudeDefaultModels is required" });
        return;
      }
      const dir = path.dirname(claudePath);
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }
      let root: Record<string, unknown> = {};
      if (fs.existsSync(claudePath)) {
        try {
          root = JSON.parse(fs.readFileSync(claudePath, "utf-8")) as Record<string, unknown>;
        } catch {
          root = {};
        }
      }
      const env = { ...((root.env as Record<string, unknown>) || {}) };
      const setOrDelete = (envKey: string, value: string | undefined) => {
        if (value === undefined) {
          return;
        }
        const t = String(value).trim();
        if (t === "") {
          delete env[envKey];
        } else {
          env[envKey] = t;
        }
      };
      if (m.opus !== undefined) {
        setOrDelete("ANTHROPIC_DEFAULT_OPUS_MODEL", m.opus);
      }
      if (m.sonnet !== undefined) {
        setOrDelete("ANTHROPIC_DEFAULT_SONNET_MODEL", m.sonnet);
      }
      if (m.haiku !== undefined) {
        setOrDelete("ANTHROPIC_DEFAULT_HAIKU_MODEL", m.haiku);
      }
      root.env = env;
      fs.writeFileSync(claudePath, `${JSON.stringify(root, null, 2)}\n`, "utf-8");
      sendJson(res, 200, {
        status: "ok",
        message: `Updated Claude default model env in ${claudePath}`,
      });
      return;
    }

    if (target === "claudeCode") {
      if (existingClaude.status === "wrong_target" && !overwrite) {
        sendJson(res, 409, {
          status: "error",
          code: "NEEDS_OVERWRITE",
          message:
            "Claude Code settings point to a different base URL. Confirm overwrite to apply CCRelay defaults.",
        });
        return;
      }
      if (existingClaude.status === "invalid" && !overwrite) {
        sendJson(res, 409, {
          status: "error",
          code: "NEEDS_OVERWRITE",
          message: "settings.json is not valid JSON. Overwrite to replace with a fresh template.",
        });
        return;
      }

      const dir = path.dirname(claudePath);
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }
      let root: Record<string, unknown> = {};
      if (fs.existsSync(claudePath)) {
        try {
          root = JSON.parse(fs.readFileSync(claudePath, "utf-8")) as Record<string, unknown>;
        } catch {
          root = {};
        }
      }
      const oldEnv = (root.env as Record<string, unknown>) || {};
      const merged = { ...oldEnv, ...buildClaudeDefaultEnv(port) };
      root.env = merged;
      fs.writeFileSync(claudePath, `${JSON.stringify(root, null, 2)}\n`, "utf-8");
      sendJson(res, 200, { status: "ok", message: `Updated ${claudePath}` });
      return;
    }

    if (target === "codex") {
      if (existingCodex.status === "wrong_target" && !overwrite) {
        sendJson(res, 409, {
          status: "error",
          code: "NEEDS_OVERWRITE",
          message:
            "Codex config points elsewhere. Confirm overwrite to replace with the CCRelay template.",
        });
        return;
      }
      const dir = path.dirname(codexPath);
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }
      fs.writeFileSync(codexPath, buildCodexTemplate(port), "utf-8");
      sendJson(res, 200, { status: "ok", message: `Updated ${codexPath}` });
    }
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown error";
    sendJson(res, 500, { status: "error", message });
  }
}
